apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: worker-org
  namespace: gce-production-1
spec:
  chart:
    path: charts/gce-worker
    git: git@github.com:travis-ci/kubernetes-config.git
    ref: master
  releaseName: worker-org
  values:
    image:
      repository: travisci/worker
      tag: v6.2.17

    cluster:
      enabled: true
      maxJobs: 300
      maxJobsPerWorker: 50

    site: org
    queue: builds.gce
    project: eco-emissary-99515
    librato_source_prefix: production-1-gce

    trvs:
      enabled: true
      app: gce-workers
      env: production-1
      pro: false

    rateLimitRedis:
      enabled: true
      secretName: rate-limit-redis
      envPrefix: RATE_LIMIT_REDIS

    default_machine_type: "n2-standard-2"
    worker_gce_zones: "us-east1-c,us-east1-d"
    default_gce_network: "main-us-east1"
    worker_gce_region: "us-east1"
