---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: fluxbot
  namespace: gce-staging-services-1
spec:
  chart:
    path: charts/fluxbot
    git: git@github.com:travis-infrastructure/kubernetes-config.git
    ref: staging
  releaseName: fluxbot
  values:
    image:
      repository: gcr.io/travis-ci-staging-services-1/fluxbot
      tag: '7cf484a'
      pullPolicy: IfNotPresent
    replicaCount: 1
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: contour
        certmanager.k8s.io/cluster-issuer: letsencrypt-staging
        ingress.kubernetes.io/force-ssl-redirect: "true"
        kubernetes.io/tls-acme: "true"
        contour.heptio.com/tls-minimum-protocol-version: "1.2"
      hosts:
      - fluxbot-staging.travis-ci.org
      tls:
      - secretName: fluxbot-staging-travis-ci-org-tls
        hosts:
        - fluxbot-staging.travis-ci.org
