---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: node-red
  namespace: gce-staging-services-1
  annotations:
    flux.weave.works/automated: 'true'
spec:
  chart:
    path: charts/node-red
    git: git@github.com:travis-ci/kubernetes-config.git
    ref: staging
  releaseName: node-red
  values:
    replicaCount: 1
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: contour
        certmanager.k8s.io/cluster-issuer: letsencrypt-staging
        ingress.kubernetes.io/force-ssl-redirect: "true"
        kubernetes.io/tls-acme: "true"
        contour.heptio.com/tls-minimum-protocol-version: "1.2"
      hosts:
        - nodered.staging.travis-ci.org
      tls:
        - secretName: nodered-staging-travis-ci-org-tls
          hosts:
          - nodered.staging.travis-ci.org



