---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: shield-com
  namespace: gce-staging-services-1
spec:
  chart:
    path: charts/shield
    git: git@github.com:travis-infrastructure/kubernetes-config.git
    ref: staging
  releaseName: shield-com
  values:
    image:
      repository: gcr.io/travis-ci-staging-services-1/shield
      tag: 'efda8fc'
      pullPolicy: IfNotPresent
    replicaCount: 2
    vault:
      secret: shield-com-staging
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: contour
        certmanager.k8s.io/cluster-issuer: letsencrypt-staging
        ingress.kubernetes.io/force-ssl-redirect: "true"
        kubernetes.io/tls-acme: "true"
        contour.heptio.com/tls-minimum-protocol-version: "1.2"
      hosts:
      - api-staging.travis-ci.com
      - shield-staging.travis-ci.com
      tls:
      - secretName: api-staging-travis-ci-com-tls
        hosts:
        - api-staging.travis-ci.com
      - secretName: shield-staging-travis-ci-com-tls
        hosts:
        - shield-staging.travis-ci.com
