---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: travis-listener-pro
  namespace: gce-staging-services-1
spec:
  chart:
    path: charts/travis-listener
    git: git@github.com:travis-ci/kubernetes-config.git
    ref: staging
  releaseName: travis-listener-pro
  values:
    image:
      repository: gcr.io/travis-ci-staging-services-1/travis-listener:v1.0.5-21-ge897c14
      tag: v1.0.5-21-ge897c14
      pullPolicy: IfNotPresent
    vault:
      secret: travis-pro-listener-staging-com
    trvs:
      enabled: true
      env: staging-1
      pro: true
    replicaCount: 2
    env:
      RACK_ENV: production
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: contour
        certmanager.k8s.io/cluster-issuer: letsencrypt-staging
        ingress.kubernetes.io/force-ssl-redirect: "true"
        kubernetes.io/tls-acme: "true"
        contour.heptio.com/tls-minimum-protocol-version: "1.2"
      hosts:
      - host: notify-staging.travis-ci.com
        paths: ["/"]
      - host: notify.staging.travis-ci.com
        paths: ["/"]
      tls:
      - secretName: notify-staging-travis-ci-com-tls
        hosts:
        - notify-staging.travis-ci.com
        - notify.staging.travis-ci.com
