---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: travis-vcs-pro
  namespace: gce-staging-services-1
  annotations:
    flux.weave.works/automated: 'true'
spec:
  chart:
    path: charts/travis-vcs
    git: git@github.com:travis-ci/kubernetes-config.git
    ref: staging
  releaseName: travis-vcs-pro
  values:
    image:
      repository: quay.io/travisci/travis-vcs
      tag: 'e33e604'
    imagePullSecrets:
    - name: travisci-travis-vcs-pull-secret
    trvs:
      enabled: true
      env: staging-1
      pro: true
    replicaCount: 2
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: contour
        certmanager.k8s.io/cluster-issuer: letsencrypt-staging
        ingress.kubernetes.io/force-ssl-redirect: "true"
        kubernetes.io/tls-acme: "true"
        contour.heptio.com/tls-minimum-protocol-version: "1.2"
      hosts:
      - host: vcs-staging.travis-ci.com
        paths: ["/"]

      tls:
      - secretName: vcs-staging-travis-ci-com-tls
        hosts:
        - vcs-staging.travis-ci.com
