---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: vault
  namespace: gce-staging-services-1
  annotations:
    flux.weave.works/automated: 'true'
spec:
  chart:
    path: charts/vault
    git: git@github.com:travis-ci/kubernetes-config.git
    ref: staging
  releaseName: vault
  values:
    replicaCount: 1
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: contour
      hosts:
      - host: vault.staging.travis-ci.org
        paths: ["/"]
    appHost: vault.staging.travis-ci.org
