---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: gcloud-cleanup
  namespace: default
  annotations:
    flux.weave.works/tag.gcloud-cleanup: glob:test-*
    flux.weave.works/automated: 'false'
spec:
  chart:
    path: charts/gcloud-cleanup
    git: git@github.com:travis-infrastructure/kubernetes-config.git
    ref: staging
  releaseName: gcloud-cleanup
  values:
    image:
      repository: travisci/gcloud-cleanup
      tag: 4890bc7
    trvs:
      enabled: true
      env: staging-1
      pro: false
    rateLimitRedis:
      enabled: true
      secretName: rate-limit-redis
      envPrefix: RATE_LIMIT_REDIS
    replicaCount: 1
