---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: staging-travis-lxd-images
  namespace: gce-travis-ci-staging-1 
spec:
  chart:
    path: charts/travis-lxd-images
    git: git@github.com:travis-infrastructure/kubernetes-config.git
    ref: master
  releaseName: travis-staging-lxd-images
  values:
    image:
      repository: gcr.io/travis-ci-prod-services-1/lxd-images-server
      tag: v0.0.5-3-g8a63430
      pullPolicy: Always
    vault:
      secret: travis-lxd-images-staging-com
    replicaCount: 2
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
        cert-manager.io/cluster-issuer: "letsencrypt-staging"
        kubernetes.io/tls-acme: "true"
      hosts:
      - host: staging-lxd-images.travis-ci.com
        paths: ["/"]
      tls:
      - secretName: lxd-images-staging-travis-ci-com-tls
        hosts:
        - staging-lxd-images.travis-ci.com