---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: travis-autoscaler
  namespace: default
spec:
  chart:
    path: charts/travis-autoscaler
    git: git@github.com:travis-ci/kubernetes-config.git
    ref: staging
  releaseName: travis-autoscaler
  values:
    image:
      repository: quay.io/travisci/autoscaler
      tag: v0.2.12-5-gfe31641
      pullPolicy: IfNotPresent
    imagePullSecrets:
      - name: travisci-travis-autoscaler-pull-secret
    vault:
      secret: travis-autoscaler-staging-com
    replicaCount: 1
