apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: worker-org-k8s-queue
  namespace: default
spec:
  chart:
    path: charts/gce-worker
    git: git@github.com:travis-infrastructure/kubernetes-config.git
    ref: staging
  releaseName: worker-org-k8s-queue
  values:
    image:
      repository: travisci/worker
      tag: v6.2.1

    cluster:
      enabled: true
      maxJobs: 20
      maxJobsPerWorker: 10

    site: org
    queue: builds.k8s
    project: travis-staging-1
    librato_source_prefix: staging-1-gce

    trvs:
      enabled: true
      app: gce-workers
      env: staging-2
      pro: false

    rateLimitRedis:
      enabled: true
      secretName: rate-limit-redis
      envPrefix: RATE_LIMIT_REDIS
