# Default values for travis-gatekeeper.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: quay:io/travisci/travis-gatekeeper
  tag: ''
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

trvs:
  # If not enabled, be sure to set secretName and create a secret with the
  # necessary environment variables for travis-listener
  enabled: false
  app: "gatekeeper"
  env: ""
  pro: false

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []

  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local
