apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gcloud-cleanup.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "gcloud-cleanup.name" . }}
    helm.sh/chart: {{ include "gcloud-cleanup.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "gcloud-cleanup.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "gcloud-cleanup.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          livenessProbe:
            exec:
              command:
                - ps | grep [g]cloud-cleanup
            initialDelaySeconds: 10
            periodSeconds: 130
          env:
            {{ range $key, $value := .Values.env }}
            - name: "{{ $key }}"
              value: "{{ $value }}"
            {{ end }}
          {{- if .Values.redis.enabled }}
            - name: GCLOUD_CLEANUP_RATE_LIMIT_REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "gcloud-cleanup.redis.fullname" . }}
                  key: redis-password
            - name: GCLOUD_CLEANUP_RATE_LIMIT_REDIS_URL
              value: redis://:$(GCLOUD_CLEANUP_RATE_LIMIT_REDIS_PASSWORD)@$(GCLOUD_CLEANUP_REDIS_MASTER_SERVICE_HOST):$(GCLOUD_CLEANUP_REDIS_MASTER_SERVICE_PORT)
          envFrom:
            - secretRef:
                name: {{ template "gcloud-cleanup.secret" . }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
