---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: rate-limit-redis
  namespace: gce-production-3
spec:
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: redis
    version: 8.0.13
  releaseName: rate-limit-redis
  values:
    cluster:
      enabled: false
    master:
      persistence:
        enabled: false
