apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: worker-premium-n2
  namespace: gce-production-3
spec:
  chart:
    path: charts/gce-worker
    git: git@github.com:travis-infrastructure/kubernetes-config.git
    ref: master
  releaseName: worker-premium-n2
  values:
    image:
      repository: travisci/worker
      tag: v6.2.6

    cluster:
      enabled: true
      maxJobs: 5
      maxJobsPerWorker: 5

    site: com
    queue: builds.us-east1-test
    project: travis-ci-prod-3
    librato_source_prefix: production-3-gce

    trvs:
      enabled: true
      app: gce-workers
      env: production-3
      pro: true

    rateLimitRedis:
      enabled: true
      secretName: rate-limit-redis
      envPrefix: RATE_LIMIT_REDIS

    default_machine_type: "n1-standard-2"
    premium_machine_type: "n2-standard-16"
    worker_gce_zone: "us-east1-c,us-east1-d"
    default_gce_network: "main-us-east1"
    worker_gce_region: "us-east1"
