apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: jupiter-brain-org
  namespace: macstadium-prod-1
spec:
  chart:
    path: charts/jupiter-brain
    git: git@github.com:travis-infrastructure/kubernetes-config.git
  releaseName: jupiter-brain-org
  values:
    image:
      tag: v1.1.0
    trvs:
      enabled: true
      env: production-1
    honeycomb:
      dataset: jb-requests
      sampleRate: 10
