apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: jupiter-brain-com
  namespace: macstadium-prod-1
spec:
  chart:
    path: charts/jupiter-brain
    git: git@github.com:travis-ci/kubernetes-config.git
  releaseName: jupiter-brain-com
  values:
    image:
      tag: v1.2.1
    trvs:
      enabled: true
      env: production-1
      pro: true
    honeycomb:
      dataset: jb-requests
      sampleRate: 10
