apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: jupiter-brain-custom-7
  namespace: macstadium-prod-1
spec:
  chart:
    path: charts/jupiter-brain
    git: git@github.com:travis-infrastructure/kubernetes-config.git
  releaseName: jupiter-brain-custom-7
  values:
    trvs:
      enabled: true
      env: custom-7-1
      pro: true
    honeycomb:
      dataset: jb-requests
      sampleRate: 1
