apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: worker-com
  namespace: macstadium-prod-1
spec:
  chart:
    path: charts/macstadium-worker
    git: git@github.com:travis-ci/kubernetes-config.git
  releaseName: worker-com
  values:
    image:
      tag: v6.2.0

    cluster:
      enabled: true
      maxJobs: 82
      maxJobsPerWorker: 20

    site: com
    jupiterBrainName: jupiter-brain-com

    trvs:
      enabled: true
      app: macstadium-workers
      env: production-common
      pro: true
