apiVersion: helm.integrations.flux.weave.works/v1alpha2
kind: FluxHelmRelease
metadata:
  name: worker-com
  namespace: macstadium-prod-1
  labels:
    chart: macstadium-worker
spec:
  chartGitPath: macstadium-worker
  releaseName: worker-com
  values:
    image:
      tag: v5.0.0
    # Eventually this should be:
    # replicaCount: 5
    replicaCount: 1
    site: com

    concurrency:
      poolSize: 21
      totalJobs: 21 # eventually 105ish
      redis:
        name: worker-redis

    jupiterBrainName: jupiter-brain-com
    secretEnv: production-common
