apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: worker-custom-2
  namespace: macstadium-prod-1
spec:
  chart:
    path: charts/macstadium-worker
    git: git@github.com:travis-infrastructure/kubernetes-config.git
  releaseName: worker-custom-2
  values:
    image:
      tag: v6.2.0

    cluster:
      enabled: true
      maxJobs: 3
      maxJobsPerWorker: 3

    site: com
    jupiterBrainName: jupiter-brain-custom-2
    queue: ""

    trvs:
      enabled: true
      app: macstadium-workers
      env: custom-2
      pro: true
