apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: worker-custom-4
  namespace: macstadium-prod-1
spec:
  chart:
    path: charts/macstadium-worker
    git: git@github.com:travis-infrastructure/kubernetes-config.git
  releaseName: worker-custom-4
  values:
    image:
      tag: v6.2.0

    cluster:
      enabled: true
      maxJobs: 5
      maxJobsPerWorker: 5

    site: org
    jupiterBrainName: jupiter-brain-custom-4
    queue: ""

    trvs:
      enabled: true
      app: macstadium-workers
      env: custom-4
