apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: worker-com
  namespace: macstadium-prod-1
spec:
  chart:
    path: charts/macstadium-worker
    git: https://github.com/travis-ci/kubernetes-config.git
  releaseName: worker-com
  values:
    image:
      tag: v5.0.0
    # Eventually this should be:
    # replicaCount: 5
    replicaCount: 1
    site: com
    poolSize: 21
    jupiterBrainName: jupiter-brain-com
    secretEnv: production-common
