apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: worker-premium-c2
  namespace: gce-production-3
spec:
  chart:
    path: charts/gce-worker
    git: git@github.com:travis-ci/kubernetes-config.git
    ref: master
  releaseName: worker-premium-c2
  values:
    image:
      repository: travisci/worker
      tag: v6.2.1-21-g73afc12

    cluster:
      enabled: true
      maxJobs: 0
      maxJobsPerWorker: 50

    site: com
    queue: builds.gce-premium-c2
    project: travis-ci-prod-3
    librato_source_prefix: production-3-gce

    trvs:
      enabled: true
      app: gce-workers
      env: production-3
      pro: true

    rateLimitRedis:
      enabled: true
      secretName: rate-limit-redis
      envPrefix: RATE_LIMIT_REDIS

    default_machine_type: "n1-standard-2"
    premium_machine_type: "c2-standard-4"
    worker_gce_zone: "us-central1-f"
