apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: vsphere-janitor-custom-1
  namespace: macstadium-prod-2
spec:
  chart:
    path: charts/vsphere-janitor
    git: git@github.com:travis-ci/kubernetes-config.git
  releaseName: vsphere-janitor-custom-1
  values:
    trvs:
      enabled: true
      env: custom-1-2
      pro: false
