apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: worker-com
  namespace: macstadium-prod-2
spec:
  chart:
    path: charts/macstadium-worker
    git: git@github.com:travis-infrastructure/kubernetes-config.git
  releaseName: worker-com
  values:
    image:
      tag: v6.2.0

    cluster:
      enabled: true
      maxJobs: 120
      maxJobsPerWorker: 30

    site: com
    jupiterBrainName: jupiter-brain-com

    trvs:
      enabled: true
      app: macstadium-workers
      env: production-common
      pro: true
