{{- if .Values.rbac.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "contour.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "contour.name" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "contour.fullname" . }}
    namespace: {{ .Release.Namespace }}
{{ end }}
