apiVersion: v1
kind: Service
metadata:
  name: {{ template "contour.fullname" . }}
  labels:
    app: {{ template "contour.name" . }}
    chart: {{ template "contour.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    {{- with .Values.service.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
    {{- end }}
spec:
  externalTrafficPolicy: "{{ .Values.service.externalTrafficPolicy }}"
  type: {{ .Values.service.type }}
{{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: "{{ .Values.service.loadBalancerIP }}"
{{- end }}
  ports:
   - port: 80
     name: http
     protocol: TCP
     targetPort: 8080
   - port: 443
     name: https
     protocol: TCP
     targetPort: 8443
  selector:
    app: {{ template "contour.name" . }}
    release: {{ .Release.Name }}
