apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: worker-com-free
  namespace: gce-production-1
spec:
  chart:
    path: charts/gce-worker
    git: git@github.com:travis-ci/kubernetes-config.git
    ref: master
  releaseName: worker-com-free
  values:
    image:
      repository: travisci/worker
      tag: v6.2.22

      # Calculation: 17000 CPUs / 2 vCPU per job / 2 worker types per project = 4250 maxJobs per worker type
      # Take a bit of headroom, don't go over 4000 maxJobs
      # NOTE: com-free is not in use atm.
    cluster:
      enabled: true
      maxJobs: 0
      maxJobsPerWorker: 1

    site: com
    queue: builds.gce-free
    project: eco-emissary-99515
    librato_source_prefix: production-1-gce

    trvs:
      enabled: true
      app: gce-workers
      env: production-1
      pro: true

    rateLimitRedis:
      enabled: true
      secretName: rate-limit-redis
      envPrefix: RATE_LIMIT_REDIS
