apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: worker-premium-hack
  namespace: gce-production-1
spec:
  chart:
    path: charts/gce-worker
    git: git@github.com:travis-infrastructure/kubernetes-config.git
    ref: master
  releaseName: worker-premium-hack
  values:
    image:
      repository: travisci/worker
      tag: v6.2.0-6-ga7e15a0

    cluster:
      enabled: true
      maxJobs: 0
      maxJobsPerWorker: 50

    site: com
    queue: builds.gce-premium-hack
    project: eco-emissary-99515
    librato_source_prefix: production-1-gce

    trvs:
      enabled: true
      app: gce-workers
      env: production-1
      pro: true

    rateLimitRedis:
      enabled: true
      secretName: rate-limit-redis
      envPrefix: RATE_LIMIT_REDIS

    default_machine_type: "n1-standard-2"
    premium_machine_type: "n1-standard-8"
