apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: collectd-vsphere
  namespace: macstadium-staging
spec:
  chart:
    path: charts/collectd-vsphere
    git: git@github.com:travis-infrastructure/kubernetes-config.git
    ref: staging
  releaseName: collectd-vsphere
  values:
    trvs:
      enabled: true
      env: staging-1
