apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: statsd
  namespace: kube-system
spec:
  chart:
    path: charts/statsd
    git: git@github.com:travis-ci/kubernetes-config.git
    ref: staging
  releaseName: statsd
  values:
    secretEnv: macstadium_staging
