apiVersion: helm.integrations.flux.weave.works/v1alpha2
kind: FluxHelmRelease
metadata:
  name: vsphere-monitor
  namespace: macstadium-staging
  labels:
    chart: vsphere-monitor
spec:
  chartGitPath: vsphere-monitor
  releaseName: vsphere-monitor
  values:
    secretEnv: common-1
