apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: worker-org
  namespace: macstadium-staging
spec:
  chart:
    path: charts/macstadium-worker
    git: git@github.com:travis-infrastructure/kubernetes-config.git
    ref: staging
  releaseName: worker-org
  values:
    image:
      tag: v6.2.0

    cluster:
      enabled: true
      maxJobs: 8
      maxJobsPerWorker: 2

    site: org
    jupiterBrainName: jupiter-brain-org

    trvs:
      enabled: true
      app: macstadium-workers
      env: staging-common
