apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: worker-com
  namespace: macstadium-staging
spec:
  chart:
    path: charts/macstadium-worker
    git: https://github.com/travis-ci/kubernetes-config.git
    ref: staging
  releaseName: worker-com
  values:
    image:
      tag: v5.0.0
    replicaCount: 4
    site: com
    poolSize: 2
    jupiterBrainName: jupiter-brain-com
    secretEnv: staging-common
