---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: gcloud-cleanup
  namespace: gce-production-4
  annotations:
    flux.weave.works/tag.gcloud-cleanup: glob:test-*
    flux.weave.works/automated: 'false'
spec:
  chart:
    path: charts/gcloud-cleanup
    git: git@github.com:travis-ci/kubernetes-config.git
    ref: master
  releaseName: gcloud-cleanup
  values:
    image:
      repository: travisci/gcloud-cleanup
      tag: 4890bc7
    trvs:
      enabled: true
      env: production-4
      pro: false
    rateLimitRedis:
      enabled: true
      secretName: rate-limit-redis
      envPrefix: RATE_LIMIT_REDIS
    replicaCount: 1