apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: worker-org
  namespace: gce-production-2
spec:
  chart:
    path: charts/gce-worker
    git: git@github.com:travis-ci/kubernetes-config.git
    ref: master
  releaseName: worker-org
  values:
    image:
      repository: gcr.io/travis-ci-prod-services-1/worker
      tag: v6.2.20

    cluster:
      enabled: true
      maxJobs: 200
      maxJobsPerWorker: 50

    site: org
    queue: builds.gce-paid
    project: travis-ci-prod-2
    librato_source_prefix: production-2-gce

    trvs:
      enabled: true
      app: gce-workers
      env: production-2
      pro: false

    rateLimitRedis:
      enabled: true
      secretName: rate-limit-redis
      envPrefix: RATE_LIMIT_REDIS

    default_machine_type: "n2-standard-2"
    worker_gce_zones: "us-central1-c,us-central1-f,us-central1-a"
