RELEASE_NAME = 'production'

def context_name; File.basename(Dir.pwd); end

task :apply do
  sh "helm dep update"
  sh "helm upgrade --install --kube-context=#{context_name} #{RELEASE_NAME} ."
end

task :status do
  sh "helm status --kube-context=#{context_name} #{RELEASE_NAME}"
end
