apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: travis-listener
  namespace: gce-staging-1
  annotations:
    flux.weave.works/automated: 'true'
spec:
  chart:
    path: charts/travis-listener
    git: git@github.com:travis-ci/kubernetes-config.git
    ref: staging
  releaseName: travis-listener
  values:
    image:
      repository: quay.io/travisci/travis-listener
      tag: 'v1.0.5'
    trvs:
      enabled: true
      env: staging-1
      pro: false
    replicaCount: 2
    env:
      RACK_ENV: production
    ingress:
      enabled: true
      annotations:
        certmanager.k8s.io/cluster-issuer: letsencrypt-staging
        ingress.kubernetes.io/force-ssl-redirect: "true"
        kubernetes.io/tls-acme: "true"
        contour.heptio.com/tls-minimum-protocol-version: "1.2"
      hosts:
      - host: notify.staging.travis-ci.org
        paths: ["/"]

      tls:
      - secretName: notify-staging-travis-ci-org-tls
        hosts:
        - notify.staging.travis-ci.org
