---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: travis-vcs
  namespace: gce-staging-1
  annotations:
    flux.weave.works/automated: 'true'
spec:
  chart:
    path: charts/travis-vcs
    git: git@github.com:travis-ci/kubernetes-config.git
    ref: staging
  releaseName: travis-vcs
  values:
    image:
      repository: quay.io/travisci/travis-vcs
      tag: 64742f5
    imagePullSecrets:
    - name: travisci-travis-vcs-pull-secret
    trvs:
      enabled: true
      env: staging-1
      pro: false
    replicaCount: 2
